
CREATE PROCEDURE SEIDR.[usp_DatamanagerTest2]
    @ID int output
AS
BEGIN
	INSERT INTO SEIDR.DM_Test(DC)
	VALUES(GETDATE())
    SET @ID = SCOPE_IDENTITY()
	SELECT * FROM SEIDR.DM_TEST
    RETURN 1
END